kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: role-m7-service-account
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["appstudio.redhat.com"]
  resources: ["enterprisecontractpolicies"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: role-m7-service-account-binding
subjects:
- kind: ServiceAccount
  name: m7-service-account
roleRef:
 kind: Role
 name: role-m7-service-account
 apiGroup: rbac.authorization.k8s.io
